// ===================================
// 隣に、君がいる — シナリオデータ
// ===================================
// 編集ガイド：
//   s: 話者名（'葵' / '澪' / '上司'）
//   t: 台詞テキスト（\nで改行）
//   n: ナレーション（sなしで使う）
//   voice: ボイスファイル名（aoi_01など）
//   bg: 背景グラデ（'bg-office' / 'bg-night'）
//   bgImg: 背景画像ファイル名
//   chara: 立ち絵表示（true/false）
//   charaImg: 立ち絵ファイル名
//   heart: ♡エフェクト（true）
//   chapterLabel/chapterText: チャプタータイトル
//   narration: ナレーション文体（true）
// ===================================

const script = [
  // --- PROLOGUE ---
  {chapterLabel:'Prologue', chapterText:'まさか、君が', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'四月の第二週。\n月曜の朝礼は、いつも通り十分で終わった。\n最後に上司が言った。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {s:'上司', t:'来週から、中途採用の方が一名加わります。白石 葵さんです。営業企画の経験があるので、即戦力として活躍してもらう予定です。よろしくお願いします。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'それだけだった。\nみんな特に反応もなく、各自の席に戻っていった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'澪も戻ろうとした。\nでも、足が一瞬だけ止まった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {s:'澪', t:'（——白石、葵。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'まさか、と思った。\nでも、そんなに珍しい名前でもない。\n同じ名前の別人なんて、いくらでもいる。\n四年も経ってるんだし。\nそもそも、もう終わったことだし。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {s:'澪', t:'（違う。絶対違う。気にしない。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'自分の席に座って、パソコンを開いた。\n画面の文字が、しばらく頭に入ってこなかった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'次の月曜日。\n澪はいつもより十分早く出社した。\n理由は特にない、と自分に言い聞かせた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'午前十時。会議室に全員が集まった。\nドアが開いた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {s:'澪', t:'（——あ。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'一瞬で、わかった。\n黒い髪。静かな目。\n少しだけ前より大人になった顔。\nでも、間違えるわけがなかった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'白石 葵。\n学生の頃、ずっと好きだった人。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'白石 葵です。前職では営業企画を担当していました。まだ慣れないことも多いと思いますが、迷惑をかけないよう努めます。よろしくお願いします。', voice:'aoi_01', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'短い。でも、変に媚びていない。\n愛想笑いも、緊張した様子もない。\nただ、静かにそこに立っていた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'澪は気づかれないように、ゆっくり息を吐いた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（覚えてないよな。）\n（同じクラスだったけど、そんなに話したわけじゃない。）\n（私が勝手に好きだっただけだし。）\n（一度も話しかけられなかったし。）\n（卒業の日に、心の中でちゃんとお別れしたし。）\n（せいせいした、って思ったし。）\n（——本当に？）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'自分でツッコんで、目を閉じた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（……うるさい。終わったことだから。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'その日、白石さんの隣の席が澪に割り振られた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（なんで。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'午後。葵は黙って引き継ぎ資料を読んでいた。\n澪は自分の仕事をしながら、気配だけを感じていた。\n葵はほとんど動かない。\nコーヒーも飲まず、スマホも触らず、ただ読んでいる。\n集中すると完全に静止する人だった。\n学生の頃もそうだった。\n授業中、ずっと黒板を見ていた。\n横顔がきれいだと思って、ノートに落書きしたことがある。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（……思い出さなくていいから。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'昼休み。みんなが挨拶しに行く中、葵は一人でパソコンに向かっていた。\nお弁当を広げながら、なんとなく横目で見ていた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（変わってないな。昔から、あんな感じだった。）\n（クラスでも、誰かと群れてるところ見たことなかった。）\n（お昼も一人で食べてて、でも全然寂しそうじゃなくて。）\n（むしろ、一人の方が好きなんだろうなって思ってた。）\n（それが、なんか、好きだったんだよな——）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'思考を止めた。\nお弁当のふたを閉めた。\n食欲がなくなった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（やめやめ。終わったことだから。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:false},
  {n:'帰り際。エレベーターのボタンを押したとき。\n後ろから声がした。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:false},
  {s:'葵', t:'一ノ瀬さん。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'振り返ると、葵が立っていた。\nバッグを肩にかけて、まっすぐ澪を見ていた。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'え……はい、なんですか？', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'今日の引き継ぎ資料、わかりやすくまとめてくれていましたね。助かりました。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'あ……ありがとうございます。私が作ったわけじゃないんですけど、去年整理し直したやつで。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'そうなんですか。でも、読みやすかったです。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'エレベーターが来た。\n二人で乗り込んで、一階で扉が開いて、ロビーで別れた。\n葵は「お疲れ様でした」とだけ言って、先に出ていった。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:false},
  {s:'澪', t:'（覚えてない。やっぱり、覚えてない。）\n（当たり前だよ。向こうは何も知らないんだから。）\n（私が一方的に好きだっただけで、葵にとっては赤の他人で。）\n（それは昔も今も、変わらない。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:false},
  {n:'わかっていた。\nちゃんとわかっていた。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:false},
  {s:'澪', t:'（なんでまだ、心臓がうるさいんだろ。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'その夜、お風呂に入りながら、ずっとそのことを考えていた。\nシャワーを浴びながら、葵の声を思い出した。\n「一ノ瀬さん」って呼ばれた瞬間を、何度も再生してしまった。\nやめろ、と思った。\nでも止まらなかった。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {s:'澪', t:'（もう終わったはずだった。）\n（卒業の日、ちゃんと心の中で別れを告げた。）\n（せいせいした、って思った。）\n（四年間、一度も思い出さなかった。）\n（——本当に？）\n（……まずい。全然、終わってなかった。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},

  // --- CHAPTER 1 ---
  {chapterLabel:'Chapter 1', chapterText:'距離の測り方', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'葵が来てから、二週間が経った。\n澪は葵に気づかれないように、気をつけていた。\n余計に話しかけない。目を合わせすぎない。\n名前を呼ばれてもびっくりしない。\n普通の同僚として、普通に接する。\nそれだけでよかった。\n——そのはずだった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'月曜の朝。出社したら葵はもう席についていた。\n定時より三十分早い。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（早いな。……昔からこういう人だっけ。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'思い出そうとして、やめた。\n思い出すたびに、ろくなことにならない。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'午前中、隣から静かなキーボードの音が聞こえていた。\n葵は集中するとまったく動かない。\n画面だけ見て、コーヒーも飲まずに打ち続ける。\n澪はそれを横目で見ながら、自分の仕事をした。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'一ノ瀬さん、この数字、先週のと合ってますか。', voice:'aoi_02', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'ちょっと待って……あ、ここ一桁ずれてる。先週のファイル、送りましょうか？', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'お願いできますか。', voice:'aoi_03', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'今送ります。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'ファイルを送ったら、三分後にチャットが来た。\n「ありがとうございます。助かりました。」\nそれだけだった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（また私に聞いてきた。他の人には聞かないのに。）\n（……席が隣だから。それだけ。）\n（うん、それだけ。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'そういうことが、何度かあった。\n資料の確認。会議室の場所。備品の置き場所。\nいつも、静かな声で「一ノ瀬さん」と呼んできた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（名前、呼ばれるたびにびっくりしちゃうの、なんとかならないかな。）\n（三年目なのに、新人みたいな心臓してる。）\n（情けない。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'火曜日の午後。葵が小さなため息をついた。\n珍しかった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'どうかしました？', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……このシステム、入力項目多くないですか。', voice:'aoi_04', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'あー……多いですよね。前の担当者が作ったやつで、誰も変えようとしないんですよ。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'非効率ですね。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'そうなんですよ。私もずっとそう思ってて。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……変えたら怒られますか。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（笑いながら）提案するだけなら、たぶん大丈夫ですよ。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'そうですか。じゃあ考えてみます。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（笑ってしまった。）\n（葵と、普通に話してしまった。）\n（……ダメだ。距離縮めたらダメなのに。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'水曜日。チームで小さなミスがあって、午後から空気が重かった。\n関係者がバタバタしている中、葵は黙々と自分の仕事を続けていた。\n夕方、みんなが帰り始めた頃、葵がぽつりと言った。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'あのミス、構造的な問題ですよね。個人のせいにしても、また起きますよ。\n来週の定例で、フローを見直す提案、してみようと思っていて。……一ノ瀬さん、一緒にどうですか。', voice:'aoi_05', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（え。）\n（誘われた。）\n（仕事の話だけど、誘われた。）\n（落ち着け。落ち着け、私。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'……うん、やろう。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'ありがとうございます。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'帰り道、ずっとにやけてしまって、自分が嫌になった。', bg:'bg-night', bgImg:'bg_street.png', stars:true, chara:false},
  {s:'澪', t:'（仕事の話だから。普通のことだから。）\n（「一緒にどうですか」って、誰にでも言える言葉だから。）\n（わかってる。わかってるのに。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'木曜日の昼休み。食堂が混んでいて、葵が一人でトレーを持ったまま立っているのが見えた。\nどこに座ろうか探している。\n行こうか迷って、気づいたら声をかけていた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'白石さん、こっち座ります？', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……いいんですか。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'どうぞどうぞ。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'向かい合って食べた。\n最初はほとんど無言だった。\n葵はごはんを食べながら、スマホも見ずに、ただ食べていた。\n変な人だな、と思った。でも嫌じゃなかった。\nむしろ、一緒にいて不思議と落ち着いた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'一ノ瀬さんって、この会社長いんですか。\n……四年。なんか、違うと思って出てきました。うまく言えないんですけど、やってることが自分じゃなくていい気がして。ある日急に嫌になって辞めました。貯金使いながら半年くらいぼーっとしてから、また働こうと思って。……地味ですね。', voice:'aoi_06', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'地味じゃないですよ。なんか、いいなって思いました。ちゃんと自分の声聞けてる感じがして。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'一ノ瀬さんは、ここ好きですか。この会社。\n……いいですね、それ。', voice:'aoi_07', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（あ。）\n（この人、こういうこと話すんだ。）\n（クールに見えるけど、ちゃんと自分の気持ちがある人なんだ。）\n（昔から、そうだった気がする。）\n（授業中、先生に意見を言える人だった。）\n（みんなが黙ってるとき、一人だけ手を挙げてた。）\n（かっこいいと思ってた。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'思考を止めた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（また思い出してる。やめろ。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'お昼が終わって、席に戻った。\n葵は「ごちそうさまでした」と言って、すぐに仕事に戻った。\n特別なことは何もなかった。\nただのお昼ご飯だった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（……全然、終わってない。）\n（むしろ、どんどんひどくなってる。）\n（まずい。本当にまずい。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'金曜日の夕方。葵と二人で、定例会議用の資料を作った。\n葵は無駄なことを言わない。\nでも、必要なことは全部言う。\n澪が「ここどうしますか」と聞くと、必ず自分の考えを答えた。\n「どっちでもいいです」とは言わなかった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（こういう人、一緒に仕事してて気持ちいいな。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'そう思ってから、ちょっと悲しくなった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（仕事の話だけしてれば、普通に好きになれる人なのに。）\n（もう、なってるけど。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'二時間かけて資料が完成した。\n葵が「ありがとうございました」と頭を下げた。\nほんの少しだけ、いつもより柔らかい声だった。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（……気のせいじゃないといいな。）\n（って、また。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'帰り道、夜風が少し冷たかった。\n澪は歩きながら、ため息をついた。', bg:'bg-night', bgImg:'bg_street.png', stars:true, chara:false},
  {s:'澪', t:'（どうしよう。）\n（こんなに好きになるつもりじゃなかったのに。）\n（同じ職場で、毎日隣にいて、普通に話して。）\n（無理だよ、こんなの。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'でも——', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {s:'澪', t:'（明日も会えるんだよな。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'そう思ったら、少しだけ足が軽くなった。\n自分がおかしくなりそうだった。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},

  // --- CHAPTER 2 ---
  {chapterLabel:'Chapter 2', chapterText:'一ヶ月だけ', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:false},
  {n:'月曜日の朝。\nいつも通り出社したら、葵がデスクの前で立ったままスマホを見ていた。\n座らずに、ずっと画面を見ている。\n珍しかった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'おはようございます。どうかしました？', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……おはようございます。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'葵はスマホをしまって、席に座った。\nそれだけだった。\nでも、なんとなく、いつもと違う気がした。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（なんだろ。気になる。）\n（……気にしない。仕事しよ。）', narration:true, bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'午前中はお互い黙って仕事をした。\n昼前に、葵がため息をついた。\n今週二回目だ、と澪は思った。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'また、システムですか？', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……いや、違います。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'それきり、葵は何も言わなかった。\n澪も聞かなかった。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'昼休み。食堂に向かおうとしたら、葵に呼び止められた。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'一ノ瀬さん、少しいいですか。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'はい。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……相談があって。', bg:'bg-office', bgImg:'bg_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'葵が「相談」という言葉を使うのを、初めて聞いた気がした。\n澪は椅子を引いて、向き直った。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'実は、部屋のことで困っていて。今月末で今の仮住まいを出なきゃいけないんですけど、次に入りたい部屋に、まだ前の人が住んでて。入居できるのが来月頭になってしまって。ホテルも調べたんですけど、一ヶ月だと結構な金額になってしまって。他に知り合いもいないし、どうしようかと思って。\n……図々しいのはわかってます。でも、一ノ瀬さんしか頼める人がいなくて。もし嫌なら、全然断ってもらっていいので。一ヶ月だけ、部屋に置いてもらえませんか。生活費は必ず出します。家事も手伝います。絶対に迷惑はかけません。', voice:'aoi_08', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'まっすぐな目だった。\n逃げない目。\n昔からこういう人だった。\n頼むときも、ちゃんと目を見て頼む人だった。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（え。）\n（え、え、え。）\n（毎日、同じ部屋にいるってこと？）\n（朝も夜も？）\n（一ヶ月間？）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'心臓がうるさかった。\n断る理由なんていくらでもあった。\n狭い。生活リズムが違う。そもそもまだそんなに仲良くない。\n全部、正当な理由だった。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（でも。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'葵が困っている。\n他に頼める人がいない。\nそれだけだった。\nそれだけで、もう答えは出ていた気がした。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'……わかった。いいよ。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……本当に？', voice:'aoi_09', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'うん。でも、ちゃんとルール決めよう。お互い気持ちよく過ごせるように。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'葵', t:'……ありがとうございます。本当に、助かります。', voice:'aoi_10', heart:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'葵が、少しだけ息を吐いた。\nほんの少し、肩の力が抜けた気がした。\nそんな顔、初めて見た。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {s:'澪', t:'（あ、この人にもこういう顔があるんだ。）', narration:true, bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:true, charaImg:'aoi_normal.png'},
  {n:'そう思ったら、胸がぎゅっとなった。', bg:'bg-office', bgImg:'bg_evening_office.png', stars:false, chara:false},
  {s:'澪', t:'（……私、何やってるんだろ。）\n（好きな人を、自分の部屋に住まわせるって。）\n（正気じゃない。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'でも——', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {s:'澪', t:'（後悔は、してなかった。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'その夜、帰り道に一人でルールを考えた。\n光熱費は折半。\n冷蔵庫は共有していい。\nお風呂は時間をずらす。\n休日は干渉しない。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'真面目にメモしながら、途中で手が止まった。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {s:'澪', t:'（葵が毎日うちにいる。）\n（ご飯食べて、お風呂入って、寝て。）\n（同じ空間で。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'スマホを伏せた。\n天井を見た。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {s:'澪', t:'（一ヶ月、耐えられるかな。）\n（……耐えるって何を。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'自分でツッコんで、布団をかぶった。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {s:'澪', t:'（絶対に、気づかれないようにしないと。）\n（普通の同僚として、普通に過ごす。）\n（それだけ。それだけでいい。）', narration:true, bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},
  {n:'——一ヶ月のはずだった。', bg:'bg-night', bgImg:'bg_room.png', stars:true, chara:false},

  // END
  {type:'end', bg:'bg-evening', stars:true, chara:false},
];